/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-23 11:47:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1548073366451L));
    _jspx_dependants.put("jar:file:/C:/Users/POTATO/git/potato/potato/06_Mybatis/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/POTATO/git/potato/potato/06_Mybatis/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/POTATO/git/potato/potato/06_Mybatis/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("uri : c.tld파일의 uri와 일치하도록 할 것 \r\n");
      out.write("(WebAppLibraries / taglibs-standard-impl / META-INF / maven / c.tld (이건 core꺼) \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>INDEX</title>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/js/jquery.gdocsviewer.min.js\"></script> -->\r\n");
      out.write("<script>\r\n");
      out.write("function showPdf(n){\r\n");
      out.write("\t$(\".pdf\").eq(n-1).toggle();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover{\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pdf{\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tmin-height: 500px;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label{\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tborder-radius: 10px 10px 10px 10px;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label:hover{\r\n");
      out.write("\tbackground: #48d2f9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>INDEX</h1>\r\n");
      out.write("\t<h2>student</h2>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/student/studentEnroll.do\">학생 등록 : studentEnroll.do</a>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/student/selectOne.do\">학생정보검색 : selectOne.do</a>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/student/selectList.do\">학생리스트 : selectList.do</a>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>emp</h2>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/emp/search1.do\">사원정보 : search1.do</a>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/emp/search2.do\">사원정보2 : search2.do</a>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/emp/search3.do\">사원정보3 : search3.do</a>\r\n");
      out.write("\t<a href=\"http://localhost:9090/mybatis/emp/empPagedList.do\">사원정보(paging) : empPagedList.do</a>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h2>PDF</h2>\r\n");
      out.write("\t<label for=\"pdf\" class=\"label\" onclick=\"showPdf(1);\">1_Framework.pdf</label>\r\n");
      out.write("\t<iframe id=\"framework\" name=\"pdf\" class=\"pdf\" src=\"./수업자료/pdf/1_Framework.pdf\"></iframe>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<label for=\"pdf\" class=\"label\" onclick=\"showPdf(2);\">2_Mybatis.pdf</label>\r\n");
      out.write("\t<iframe id=\"mybatis\" name=\"pdf\" class=\"pdf\" src=\"./수업자료/pdf/2_Mybatis.pdf\"></iframe>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<label for=\"pdf\" class=\"label\" onclick=\"showPdf(3);\">3_Mybatis-동적쿼리.pdf</label>\r\n");
      out.write("\t<iframe id=\"mybatis-query\" name=\"pdf\" class=\"pdf\" src=\"./수업자료/pdf/3_Mybatis-동적쿼리.pdf\"></iframe>\r\n");
      out.write("\t<!-- <iframe src=\"http://docs.google.com/viewer?embedded=true&url=' + encodeURIComponent(file) + '\" width=\"' + settings.width + '\" height=\"' + settings.height + '\" style=\"border: none;\"></iframe> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
